version: 2.1

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.10
    steps:
      - checkout

      - run:
          name: Check changed files
          command: |
            git fetch origin main
            CHANGED_FILES=$(git diff --name-only origin/main...HEAD)
            echo "$CHANGED_FILES"

            if echo "$CHANGED_FILES" | grep -q "^tests/"; then
              echo "Tests changed → continue"
            else
              echo "No test changes → stopping job"
              circleci-agent step halt
            fi

      - run:
          name: Install dependencies
          command: |
            pip install -r requirements.txt

      - run:
          name: Run tests
          command: |
            pytest tests/

workflows:
  test-workflow:
    jobs:
      - build-and-test
